"""Initial migration

Revision ID: 48b4baea3d50
Revises: None
Create Date: 2015-05-02 11:53:43.427816

"""

# revision identifiers, used by Alembic.
revision = '48b4baea3d50'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.create_table('user',
	sa.Column('username', sa.String(length=32), nullable=False),
	sa.Column('password', sa.String(length=128), nullable=False),
	sa.Column('email', sa.String(length=254), nullable=False),
	sa.Column('first_name', sa.String(length=50), nullable=False),
	sa.Column('last_name', sa.String(length=50), nullable=False),
	sa.Column('admin', sa.Boolean(), nullable=True),
	sa.PrimaryKeyConstraint('username')
	)
	op.create_table('data_amount',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_on', sa.DateTime(), nullable=True),
	sa.Column('hours_scheduled', sa.Float(), nullable=True),
	sa.Column('hours_observed', sa.Float(), nullable=True),
	sa.Column('hours_with_data', sa.Float(), nullable=True),
	sa.Column('hours_with_uvfits', sa.Float(), nullable=True),
	sa.Column('data_transfer_rate', sa.Float(), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('graph_type',
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.PrimaryKeyConstraint('name')
	)
	op.create_table('thread',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('title', sa.String(length=100), nullable=False),
	sa.Column('username', sa.String(length=32), nullable=True),
	sa.Column('created_on', sa.DateTime(), nullable=True),
	sa.Column('last_updated', sa.DateTime(), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('set',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('username', sa.String(length=32), nullable=True),
	sa.Column('name', sa.String(length=50), nullable=True),
	sa.Column('start', sa.Integer(), nullable=True),
	sa.Column('end', sa.Integer(), nullable=True),
	sa.Column('low_or_high', sa.String(length=4), nullable=True),
	sa.Column('eor', sa.String(length=4), nullable=True),
	sa.Column('total_data_hrs', sa.Float(), nullable=True),
	sa.Column('flagged_data_hrs', sa.Float(), nullable=True),
	sa.Column('created_on', sa.DateTime(), nullable=True),
	sa.ForeignKeyConstraint(['username'], ['user.username'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('comment',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('thread_id', sa.Integer(), nullable=True),
	sa.Column('text', sa.String(length=1000), nullable=False),
	sa.Column('username', sa.String(length=32), nullable=True),
	sa.Column('created_on', sa.DateTime(), nullable=True),
	sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('graph_data_source',
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('graph_type', sa.String(length=100), nullable=True),
	sa.Column('host', sa.String(length=100), nullable=True),
	sa.Column('database', sa.String(length=100), nullable=True),
	sa.Column('table', sa.String(length=100), nullable=True),
	sa.Column('obs_column', sa.String(length=100), nullable=True),
	sa.Column('projectid', sa.Boolean(), nullable=True),
	sa.Column('width_slider', sa.Boolean(), nullable=True),
	sa.ForeignKeyConstraint(['graph_type'], ['graph_type.name'], ),
	sa.PrimaryKeyConstraint('name')
	)
	op.create_table('data_source_subscriptions',
	sa.Column('username', sa.String(length=32), nullable=True),
	sa.Column('data_source', sa.String(length=100), nullable=True),
	sa.ForeignKeyConstraint(['data_source'], ['graph_data_source.name'], ),
	sa.ForeignKeyConstraint(['username'], ['user.username'], )
	)
	op.create_table('flagged_subset',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('set_id', sa.Integer(), nullable=True),
	sa.Column('start', sa.Integer(), nullable=True),
	sa.Column('end', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['set_id'], ['set.id'], ondelete='CASCADE'),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('set_subscriptions',
	sa.Column('username', sa.String(length=32), nullable=True),
	sa.Column('set_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
	sa.ForeignKeyConstraint(['username'], ['user.username'], )
	)
	op.create_table('graph_data_source_column',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('graph_data_source', sa.String(length=100), nullable=True),
	sa.Column('name', sa.String(length=100), nullable=True),
	sa.ForeignKeyConstraint(['graph_data_source'], ['graph_data_source.name'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('active_data_sources',
	sa.Column('username', sa.String(length=32), nullable=True),
	sa.Column('data_source', sa.String(length=100), nullable=True),
	sa.ForeignKeyConstraint(['data_source'], ['graph_data_source.name'], ),
	sa.ForeignKeyConstraint(['username'], ['user.username'], )
	)
	op.create_table('flagged_obs_ids',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('obs_id', sa.Integer(), nullable=True),
	sa.Column('flagged_subset_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['flagged_subset_id'], ['flagged_subset.id'], ondelete='CASCADE'),
	sa.PrimaryKeyConstraint('id')
	)
	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_table('flagged_obs_ids')
	op.drop_table('active_data_sources')
	op.drop_table('graph_data_source_column')
	op.drop_table('set_subscriptions')
	op.drop_table('flagged_subset')
	op.drop_table('data_source_subscriptions')
	op.drop_table('graph_data_source')
	op.drop_table('comment')
	op.drop_table('set')
	op.drop_table('thread')
	op.drop_table('graph_type')
	op.drop_table('data_amount')
	op.drop_table('user')
	### end Alembic commands ###
