web: gunicorn --pythonpath papersite run_app:app --log-file=- & sh background.sh
init: cd papersite;python -m app.manage db init
migrate: cd papersite;python -m app.manage db migrate
upgrade: cd papersite;python -m app.manage db upgrade
default_values: cd papersite;python -m scripts.insert_default_db_values
