"""refactored

Revision ID: 2793fef18078
Revises: 136226427639
Create Date: 2015-10-13 00:46:46.676405

"""

# revision identifiers, used by Alembic.
revision = '2793fef18078'
down_revision = '136226427639'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_paperdata():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cpu',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('user_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sys_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iowait_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('idle_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('intr_s', sa.Integer(), nullable=True),
    sa.Column('cpu_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cpu_id')
    )
    op.create_table('Filesystem',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('system', sa.String(length=100), nullable=True),
    sa.Column('total_space', sa.BigInteger(), nullable=True),
    sa.Column('used_space', sa.BigInteger(), nullable=True),
    sa.Column('free_space', sa.BigInteger(), nullable=True),
    sa.Column('percent_space', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('filesystem_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('filesystem_id')
    )
    op.create_table('Iostat',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('tps', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('read_s', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('write_s', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('bl_reads', sa.BigInteger(), nullable=True),
    sa.Column('bl_writes', sa.BigInteger(), nullable=True),
    sa.Column('iostat_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('iostat_id')
    )
    op.create_table('Log',
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table', sa.String(length=100), nullable=True),
    sa.Column('identifier', sa.String(length=200), nullable=True),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('Monitor',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('base_path', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('full_stats', sa.String(length=200), nullable=False),
    sa.Column('del_time', sa.BigInteger(), nullable=True),
    sa.Column('time_start', sa.BigInteger(), nullable=True),
    sa.Column('time_end', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('full_stats')
    )
    op.create_table('Ram',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('total', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.BigInteger(), nullable=True),
    sa.Column('free', sa.BigInteger(), nullable=True),
    sa.Column('shared', sa.BigInteger(), nullable=True),
    sa.Column('buffers', sa.BigInteger(), nullable=True),
    sa.Column('cached', sa.BigInteger(), nullable=True),
    sa.Column('bc_used', sa.BigInteger(), nullable=True),
    sa.Column('bc_free', sa.BigInteger(), nullable=True),
    sa.Column('swap_total', sa.BigInteger(), nullable=True),
    sa.Column('swap_used', sa.BigInteger(), nullable=True),
    sa.Column('swap_free', sa.BigInteger(), nullable=True),
    sa.Column('ram_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('ram_id')
    )
    op.drop_table('paperdata')
    op.create_foreign_key(None, 'File', 'Observation', ['obsnum'], ['obsnum'])
    ### end Alembic commands ###


def downgrade_paperdata():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'File', type_='foreignkey')
    op.create_table('paperdata',
    sa.Column('path', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('era', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('era_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('obsnum', mysql.BIGINT(display_width=20), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('md5sum', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('julian_day', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('julian_date', mysql.DECIMAL(precision=12, scale=5), server_default=sa.text(u"'0.00000'"), nullable=True),
    sa.Column('polarization', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('data_length', mysql.DECIMAL(precision=6, scale=5), server_default=sa.text(u"'0.00000'"), nullable=True),
    sa.Column('raw_path', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cal_path', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('npz_path', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('final_product_path', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tape_index', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('compr_file_size_MB', mysql.DECIMAL(precision=6, scale=1), server_default=sa.text(u"'0.0'"), nullable=True),
    sa.Column('raw_file_size_MB', mysql.DECIMAL(precision=10, scale=1), server_default=sa.text(u"'0.0'"), nullable=True),
    sa.Column('compressed', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('edge', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('write_to_tape', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('delete_file', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('restore_history', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('compr_md5sum', mysql.VARCHAR(length=32), server_default=sa.text(u"'NULL'"), nullable=True),
    sa.Column('npz_md5sum', mysql.VARCHAR(length=32), server_default=sa.text(u"'NULL'"), nullable=True),
    sa.Column('npz_file_size_MB', mysql.DECIMAL(precision=5, scale=1), server_default=sa.text(u"'0.0'"), nullable=True),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.drop_table('Ram')
    op.drop_table('Monitor')
    op.drop_table('Log')
    op.drop_table('Iostat')
    op.drop_table('Filesystem')
    op.drop_table('Cpu')
    ### end Alembic commands ###


def upgrade_ganglia():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cpu',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('user_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sys_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iowait_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('idle_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('intr_s', sa.Integer(), nullable=True),
    sa.Column('cpu_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cpu_id')
    )
    op.create_table('Feed',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('base_path', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('julian_day', sa.Integer(), nullable=True),
    sa.Column('is_movable', sa.Boolean(), nullable=True),
    sa.Column('is_moved', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('Filesystem',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('system', sa.String(length=100), nullable=True),
    sa.Column('total_space', sa.BigInteger(), nullable=True),
    sa.Column('used_space', sa.BigInteger(), nullable=True),
    sa.Column('free_space', sa.BigInteger(), nullable=True),
    sa.Column('percent_space', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('filesystem_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('filesystem_id')
    )
    op.create_table('Iostat',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('tps', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('read_s', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('write_s', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('bl_reads', sa.BigInteger(), nullable=True),
    sa.Column('bl_writes', sa.BigInteger(), nullable=True),
    sa.Column('iostat_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('iostat_id')
    )
    op.create_table('Log',
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table', sa.String(length=100), nullable=True),
    sa.Column('identifier', sa.String(length=200), nullable=True),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('Monitor',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('base_path', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('full_stats', sa.String(length=200), nullable=False),
    sa.Column('del_time', sa.BigInteger(), nullable=True),
    sa.Column('time_start', sa.BigInteger(), nullable=True),
    sa.Column('time_end', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('full_stats')
    )
    op.create_table('Observation',
    sa.Column('obsnum', sa.BigInteger(), nullable=False),
    sa.Column('julian_date', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('polarization', sa.String(length=4), nullable=True),
    sa.Column('julian_day', sa.Integer(), nullable=True),
    sa.Column('lst', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('era', sa.Integer(), nullable=True),
    sa.Column('era_type', sa.String(length=20), nullable=True),
    sa.Column('length', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('time_start', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('time_end', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('delta_time', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('prev_obs', sa.BigInteger(), nullable=True),
    sa.Column('next_obs', sa.BigInteger(), nullable=True),
    sa.Column('is_edge', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('obsnum'),
    sa.UniqueConstraint('next_obs'),
    sa.UniqueConstraint('prev_obs')
    )
    op.create_table('Ram',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('total', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.BigInteger(), nullable=True),
    sa.Column('free', sa.BigInteger(), nullable=True),
    sa.Column('shared', sa.BigInteger(), nullable=True),
    sa.Column('buffers', sa.BigInteger(), nullable=True),
    sa.Column('cached', sa.BigInteger(), nullable=True),
    sa.Column('bc_used', sa.BigInteger(), nullable=True),
    sa.Column('bc_free', sa.BigInteger(), nullable=True),
    sa.Column('swap_total', sa.BigInteger(), nullable=True),
    sa.Column('swap_used', sa.BigInteger(), nullable=True),
    sa.Column('swap_free', sa.BigInteger(), nullable=True),
    sa.Column('ram_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('ram_id')
    )
    op.create_table('File',
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('base_path', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('filetype', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('obsnum', sa.BigInteger(), nullable=True),
    sa.Column('filesize', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('md5sum', sa.String(length=32), nullable=True),
    sa.Column('tape_index', sa.String(length=100), nullable=True),
    sa.Column('init_host', sa.String(length=100), nullable=True),
    sa.Column('is_tapeable', sa.Boolean(), nullable=True),
    sa.Column('is_deletable', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['obsnum'], ['Observation.obsnum'], ),
    sa.PrimaryKeyConstraint('source')
    )
    op.drop_table('iostat')
    op.drop_table('ram')
    op.drop_table('monitor')
    op.drop_table('cpu')
    op.drop_table('filesystem')
    ### end Alembic commands ###


def downgrade_ganglia():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filesystem',
    sa.Column('host', mysql.VARCHAR(length=100), server_default=sa.text(u"''"), nullable=False),
    sa.Column('system', mysql.VARCHAR(length=100), server_default=sa.text(u"''"), nullable=False),
    sa.Column('total_space', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('used_space', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('free_space', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('host', 'system'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table('cpu',
    sa.Column('host', mysql.VARCHAR(length=100), server_default=sa.text(u"''"), nullable=False),
    sa.Column('cpu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_perc', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sys_perc', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('iowait_perc', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('idle_perc', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('intr_s', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('host'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table('monitor',
    sa.Column('host', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('path', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('full_path', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('full_stats', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('del_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('time_start', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('time_end', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('full_stats'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table('ram',
    sa.Column('host', mysql.VARCHAR(length=100), server_default=sa.text(u"''"), nullable=False),
    sa.Column('total', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('used', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('free', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('shared', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('buffers', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('cached', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('bc_used', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('bc_free', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('swap_total', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('swap_used', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('swap_free', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('host'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table('iostat',
    sa.Column('host', mysql.VARCHAR(length=100), server_default=sa.text(u"''"), nullable=False),
    sa.Column('device', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tps', mysql.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('read_s', mysql.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('write_s', mysql.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('bl_reads', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('bl_writes', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('host'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.drop_table('File')
    op.drop_table('Ram')
    op.drop_table('Observation')
    op.drop_table('Monitor')
    op.drop_table('Log')
    op.drop_table('Iostat')
    op.drop_table('Filesystem')
    op.drop_table('Feed')
    op.drop_table('Cpu')
    ### end Alembic commands ###

