"""source of file added

Revision ID: bff259039cf
Revises: 115cbfaabdcf
Create Date: 2015-08-13 10:18:50.819770

"""

# revision identifiers, used by Alembic.
revision = 'bff259039cf'
down_revision = '115cbfaabdcf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_paperdata():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('paperdata')
    op.add_column('file', sa.Column('source_host', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'file', 'observation', ['obsnum'], ['obsnum'])
    op.create_foreign_key(None, 'log', 'feed', ['feed_path'], ['full_path'])
    op.create_foreign_key(None, 'log', 'observation', ['obsnum'], ['obsnum'])
    op.create_foreign_key(None, 'log', 'file', ['full_path'], ['full_path'])
    ### end Alembic commands ###


def downgrade_paperdata():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'source_host')
    #op.create_table('paperdata',
    #sa.Column('path', mysql.VARCHAR(length=100), nullable=True),
    #sa.Column('era', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    #sa.Column('era_type', mysql.VARCHAR(length=100), nullable=True),
    #sa.Column('obsnum', mysql.BIGINT(display_width=20), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    #sa.Column('md5sum', mysql.VARCHAR(length=32), nullable=True),
    #sa.Column('julian_day', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    #sa.Column('julian_date', mysql.DECIMAL(precision=12, scale=5), server_default=sa.text(u"'0.00000'"), nullable=True),
    #sa.Column('polarization', mysql.VARCHAR(length=4), nullable=True),
    #sa.Column('data_length', mysql.DECIMAL(precision=6, scale=5), server_default=sa.text(u"'0.00000'"), nullable=True),
    #sa.Column('raw_path', mysql.VARCHAR(length=100), nullable=True),
    #sa.Column('cal_path', mysql.VARCHAR(length=100), nullable=True),
    #sa.Column('npz_path', mysql.VARCHAR(length=100), nullable=True),
    #sa.Column('final_product_path', mysql.VARCHAR(length=100), nullable=True),
    #sa.Column('tape_index', mysql.VARCHAR(length=100), nullable=True),
    #sa.Column('compr_file_size_MB', mysql.DECIMAL(precision=6, scale=1), server_default=sa.text(u"'0.0'"), nullable=True),
    #sa.Column('raw_file_size_MB', mysql.DECIMAL(precision=10, scale=1), server_default=sa.text(u"'0.0'"), nullable=True),
    #sa.Column('compressed', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    #sa.Column('edge', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    #sa.Column('write_to_tape', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    #sa.Column('delete_file', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    #sa.Column('restore_history', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('comments', mysql.TEXT(), nullable=True),
    #sa.Column('compr_md5sum', mysql.VARCHAR(length=32), server_default=sa.text(u"'NULL'"), nullable=True),
    #sa.Column('npz_md5sum', mysql.VARCHAR(length=32), server_default=sa.text(u"'NULL'"), nullable=True),
    #sa.Column('npz_file_size_MB', mysql.DECIMAL(precision=5, scale=1), server_default=sa.text(u"'0.0'"), nullable=True),
    #mysql_default_charset=u'latin1',
    #mysql_engine=u'MyISAM'
    #)
    ### end Alembic commands ###


def upgrade_ganglia():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_ganglia():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

