web: gunicorn --pythonpath data run_app:app --log-file=- & sh background.sh
init: cd data;python -m app.manage db init
migrate: cd data;python -m app.manage db migrate
upgrade: cd data;python -m app.manage db upgrade
default_values: cd data;python -m scripts.insert_default_db_values
