web: gunicorn --pythonpath search run_app:app --log-file=- & sh background.sh
init: cd search;python -m app.manage db init
migrate: cd search;python -m app.manage db migrate
upgrade: cd search;python -m app.manage db upgrade
default_values: cd data;python -m scripts.insert_default_db_values
